[package]
name = "brainfuck"
version = "0.1.0"
authors = ["Thomas Kühnel <kuehnelth@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
